[package]
name = "bundler"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
full_moon = { version = "0.19.0", features = ["roblox"] }
tokio = { version = "1.36.0", features = ["full"] }
