- [ ] Add CLI implementation
- [ ] Add unit tests
- [ ] Refactor, optimize code, and make it more robust
- [ ] Add more support for where acquire is used, i.e. string interpolation
- [ ] Add root file support/option in CLI